In [1]:
#Importing basic libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
arr1 = np.array(20)

In [3]:
arr1

array(20)

In [4]:
arr1.ndim

0

In [6]:
arr2 = np.array([20, 1.2, 3.5, 20, 10])
arr2.ndim

1

In [8]:
arr_exp1 = np.array({20, 1.2, 3.5, 20, 10})

In [9]:
arr_exp1

array({1.2, 10, 3.5, 20}, dtype=object)

In [10]:
arr3 = np.array([True, 1.2, 20, "Let's try"])

In [11]:
arr3

array(['True', '1.2', '20', "Let's try"], dtype='<U32')

In [15]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr4.ndim

2

In [16]:
arr4.shape

(3, 3)

In [17]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr5 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
arr5.ndim

3

In [19]:
arr5.shape

(1, 3, 3)

In [21]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [24]:
np.zeros((3,4,5)) + 1

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [25]:
np.ones((3,4,5))*2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [26]:
np.full((3,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [27]:
np.full((3,4), 5)/2

array([[2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5]])

In [28]:
np.full((3, 4), 5)%2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
arr6 = np.array([1, 10, 20])
arr7 = np.array([2.0, 22, 5])
print(arr6 + arr7)
print(arr7 - arr6)
print(arr6*arr7)
print(arr7/arr6)

[ 3. 32. 25.]
[  1.  12. -15.]
[  2. 220. 100.]
[2.   2.2  0.25]


In [36]:
arr8 = np.array([1, 10, 20])
arr9 = np.array([2.0, 22])
# print(arr8 + arr9)
# print(arr8 - arr9)
# print(arr8*arr9)
# print(arr8/arr9)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [37]:
arr10 = np.array([[1, 0, 5], [3, 2, 1], [7, 5, 1]])
arr11 = np.array([[2, 0], [10, 1], [0, 1]])
print(arr10)
print(arr11)

[[1 0 5]
 [3 2 1]
 [7 5 1]]
[[ 2  0]
 [10  1]
 [ 0  1]]


In [38]:
arr10*arr11

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [39]:
arr10@arr11

array([[ 2,  5],
       [26,  3],
       [64,  6]])

In [42]:
np.random.rand(10)

array([0.15259216, 0.37744909, 0.60895062, 0.66419949, 0.73761693,
       0.98721175, 0.74548003, 0.60004445, 0.7663409 , 0.76073325])

In [43]:
np.random.randn(10)

array([-1.40631897, -0.77513874, -0.82388151,  0.16647659, -0.63449589,
       -0.51328446,  1.03920094, -1.01138722,  1.66992694, -0.57214646])

In [44]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Last = First + (n-1)d

In [45]:
np.random.randn(12).reshape(4,3)

array([[ 1.74805446,  0.63459154,  0.07632298],
       [ 0.09994304, -0.56081906, -0.83267356],
       [-1.15755035, -0.47771488, -0.13761303],
       [-1.32577071,  2.55287397,  2.55626478]])

In [46]:
np.random.randn(12).reshape(4,2)

ValueError: cannot reshape array of size 12 into shape (4,2)

In [57]:
np.random.seed(100)
np.random.randn(12).reshape(4,3).round(2)

array([[-1.75,  0.34,  1.15],
       [-0.25,  0.98,  0.51],
       [ 0.22, -1.07, -0.19],
       [ 0.26, -0.46,  0.44]])

In [58]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [59]:
len(sns.get_dataset_names())

22

In [60]:
df = sns.load_dataset('titanic')

In [64]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [62]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [63]:
df.shape

(891, 15)

In [65]:
df.sample(5)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
272         1       2  female  41.0      0      1  19.5000        S  Second   
201         0       3    male   NaN      8      2  69.5500        S   Third   
608         1       2  female  22.0      1      2  41.5792        C  Second   
449         1       1    male  52.0      0      0  30.5000        S   First   
645         1       1    male  48.0      1      0  76.7292        C   First   

       who  adult_male deck  embark_town alive  alone  
272  woman       False  NaN  Southampton   yes  False  
201    man        True  NaN  Southampton    no  False  
608  woman       False  NaN    Cherbourg   yes  False  
449    man        True    C  Southampton   yes   True  
645    man        True    D    Cherbourg   yes  False

In [66]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [67]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [68]:
df.values

array([[0, 3, 'male', ..., 'Southampton', 'no', False],
       [1, 1, 'female', ..., 'Cherbourg', 'yes', False],
       [1, 3, 'female', ..., 'Southampton', 'yes', True],
       ...,
       [0, 3, 'female', ..., 'Southampton', 'no', False],
       [1, 1, 'male', ..., 'Cherbourg', 'yes', True],
       [0, 3, 'male', ..., 'Queenstown', 'no', True]], dtype=object)

In [69]:
df['alive'].value_counts()

alive
no     549
yes    342
Name: count, dtype: int64

In [70]:
df['alive'].value_counts(normalize = True)*100

alive
no     61.616162
yes    38.383838
Name: proportion, dtype: float64

In [71]:
df['survived'].value_counts(normalize = True)*100

survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

In [72]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [73]:
df['fare'].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: fare, dtype: float64

In [74]:
df['fare'].nunique()

248

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [76]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [77]:
df1 = df.drop(['pclass', 'survived', 'who', 'adult_male', 'embarked', 'deck'], axis = 1)

In [78]:
df1.shape

(891, 9)

In [79]:
df1.columns

Index(['sex', 'age', 'sibsp', 'parch', 'fare', 'class', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [80]:
df1[['sex', 'age', 'fare', 'alive']].head()

sex   age     fare alive
0    male  22.0   7.2500    no
1  female  38.0  71.2833   yes
2  female  26.0   7.9250   yes
3  female  35.0  53.1000   yes
4    male  35.0   8.0500    no

In [84]:
df1.isnull().sum(axis = 1)

0      0
1      0
2      0
3      0
4      0
      ..
886    0
887    0
888    1
889    0
890    0
Length: 891, dtype: int64

In [90]:
df1[df1['embark_town'].isnull()]

sex   age  sibsp  parch  fare  class embark_town alive  alone
61   female  38.0      0      0  80.0  First         NaN   yes   True
829  female  62.0      0      0  80.0  First         NaN   yes   True

In [91]:
df1.drop([61, 829], axis = 0, inplace = True)

In [92]:
df1.isnull().sum()

sex              0
age            177
sibsp            0
parch            0
fare             0
class            0
embark_town      0
alive            0
alone            0
dtype: int64

In [93]:
df1.shape

(889, 9)

In [94]:
df1.dropna().shape

(712, 9)

In [95]:
889-177

712

In [96]:
df1.head()

sex   age  sibsp  parch     fare  class  embark_town alive  alone
0    male  22.0      1      0   7.2500  Third  Southampton    no  False
1  female  38.0      1      0  71.2833  First    Cherbourg   yes  False
2  female  26.0      0      0   7.9250  Third  Southampton   yes   True
3  female  35.0      1      0  53.1000  First  Southampton   yes  False
4    male  35.0      0      0   8.0500  Third  Southampton    no   True

In [97]:
df1[df1['age'] > 60].shape[0]

21

In [98]:
df1[(df1['age'] > 60) & (df1['class'] == 'First')].shape[0]

13

In [99]:
df1[df1['age'] > 0].shape[0]

712

In [102]:
df1.describe(include = 'all').T

count unique          top freq       mean        std   min  \
sex            889      2         male  577        NaN        NaN   NaN   
age          712.0    NaN          NaN  NaN  29.642093  14.492933  0.42   
sibsp        889.0    NaN          NaN  NaN   0.524184   1.103705   0.0   
parch        889.0    NaN          NaN  NaN   0.382452   0.806761   0.0   
fare         889.0    NaN          NaN  NaN  32.096681  49.697504   0.0   
class          889      3        Third  491        NaN        NaN   NaN   
embark_town    889      3  Southampton  644        NaN        NaN   NaN   
alive          889      2           no  549        NaN        NaN   NaN   
alone          889      2         True  535        NaN        NaN   NaN   

                25%      50%   75%       max  
sex             NaN      NaN   NaN       NaN  
age            20.0     28.0  38.0      80.0  
sibsp           0.0      0.0   1.0       8.0  
parch           0.0      0.0   0.0       6.0  
fare         7.8958  14.4542  31.0  512.3292  
class           NaN      NaN   NaN       NaN  
embark_town     NaN      NaN   NaN       NaN  
alive           NaN      NaN   NaN       NaN  
alone           NaN      NaN   NaN       NaN

In [103]:
df1[(df1['fare'] > 50) & (df1['fare'] < 100)].shape[0]

105

In [105]:
df1[(df1['fare'] > 50) & (df1['fare'] < 100) & (df1['class'] == 'First')].shape[0]

84