## WEEK 1 INTRO TO PYTHON - NUMPY and PANDAS - NB1

## Q1 - What Key Python Libraries will you Import

### You always start with this in your python notebook
### with the importing of libraries you intend to use


### >>import ?? as ??


### Numpy - 
#### Numerical functions, arrays, matrices, math functions, linear algebra




### Pandas - 
#### Spreadsheet of data - dataframes!
















In [23]:
# Import Key Libraries
import numpy as np  # Import python library for math functions, arrays, linear algebra and transforms
import pandas as pd # Import python library for modification, analysis of tabular data
#
#
import warnings
warnings.simplefilter('ignore')
#
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Q2. Some Simple array and matrix multiplication

Define a 1x3 vector (array - 1D)
and a 3x3 matrix and do the matrix multiplation between the two (1x3)x(3x3)

In [ ]:
vector = np.array([1,2,3]) # A 1x3 vector array
print('The Numpy vector\n', vector)
mat = np.array([[1,2,3], [4,5,6], [7,8,9]]) # A 3x3 matrix array
print('\nThe Numpy matrix\n', mat)

In [ ]:
product = np.matmul(vector,mat) # Gives a 1x3 array output ((1x3)x(3x3) = 1x3)
print(product)

### Q3: Solve for equations x+2y+3z=30, 4x+5y+6z=36, 7x+8y+9z=42
### Essentially from above, [mat] [x y z] = [product]

In [ ]:
### Solving the simultaneous equation of above
np.linalg.solve(mat,product)

In [ ]:
# Check above
print(1*-3.6+2*-16.8+3*22.4)
print(4*-3.6+5*-16.8+6*22.4)
print(7*-3.6+8*-16.8+9*22.4)

## Few Mathematical Expressions using numpy


*  Check out this link for Numpy mathermatical functions

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html#trigonometric-functions


### Q4: Using Numpy functions invoked by using prefix np.function like np.sqrt() 
#### Evaluate following mathematical functions

    sin(90) or sin(pi/2)
    tan (60) or tan(pi/3)
    arccos(-1) in degrees using formula
    arcsin(-1) in degress using rad2deg
    cos (60) using deg2rad
    log(e^pi)
    log10(0.001)
    sqrt(3.0)
    floor of the division of 2 real numbers
    remainder of the division of 2 numbers


1. Print the Values of  
$\sin(\pi/2)$  
$\\tan(\pi/3)$

In [ ]:
print("sin pi/2 =", np.sin(np.pi/2))
print("tan pi/3 =", np.tan(np.pi/3))

In [ ]:
print('arccos(-1) in degrees =',(180/np.pi)*np.arccos(-1))
print('arcsin(-1) in degrees =',np.rad2deg(np.arcsin(-1)))
print('cos(60deg) =', np.cos(np.deg2rad(60.)))
print('log(e^pi)=', np.log(np.exp(np.pi)))
print('sqrt(3) =',np.sqrt(3.0))
print('floor of 13./3. =',np.floor_divide(13.,3.))
print('remainder(14/3) =', np.mod(14,3))
print('log(10^5)=', np.log10(10**5))

## Generation of Arrays from lists

#### Q5a: Take a list of numbers and generate an array. 
#### Q5b: Also create of list of lists and generate a matrix and do its transpose

In [ ]:
#
# 1-D row matrix/array
list=[1,2,3,4,5]
print(list,type(list))
vec=np.array(list)
print('\n1D row array\n',vec, type(vec))
#
#print a 2D 3x3 array and its transpose
mat=np.array([[1,0,2],[0,1,3],[4,0,1]])
print('\n2D 3x3 array\n',mat,type(mat))
print('\nTranspose of above matrix\n',mat.T)

### Using functions like arange, linspace, zeros and ones
#### Q6a: Generate Integer A.Ps with different common differences
#### Q6b: Break a range into equispaced numbers(float) 
#### Q6c: Reshape arrays into matrices
#### Q6d: Define a matrix of only zeroes - why would you need it?
#### Q6e: Define a matrix of ones and identity matrix of different sizes



#

In [ ]:
#
print('\033[1m'+"Note the Rules of Range and Linspace"+'\033[0m\n')
print('Print consecutive integers starting with 0 and <10')
print(np.arange(0,10),'\n')
print('Print an A.P beginning with 3 with a difference of 6 and < 24')
print(np.arange(3,24,6))
# Break the range 0-10 into default 50 equidistant points (AP with diff = range/50)
print(np.linspace(0,10)) 
print('\n') 
print('\nBreakup 0-10 range into 21 equidistant numbers inclusive of 0 and 10')
print(np.linspace(0,10,21))
print('\nReshaped array into 6x4 matrix\n',(np.linspace(0,23,24)).reshape(6,4))
print('\n3x2 zeroes\n',np.zeros([3,2]))
print('\n3x5 ones\n',np.ones([3,5]))
print('\033[1m'+ '\n6x6 IDENTITY MATRIX' +'\033[0m')
print(np.eye(6))

### Locating entries and changing values in numpy vectors/ arrays

#### Q7a:  Using Random Number generator and random values from a Std normal distribution and calculating min, max, mean, std
#### Q7b: Retrieving value(s) from a vector
#### Q7c: Reshape the vector into a matrix and modify rows, columns and elements


#


In [ ]:
# Generate a random integer from within a range
print("The random integer generated is", np.random.randint(2,52),'\n')
#
# Generate a random vector of size 24 based on a standard normal distribution
rand_vec=np.random.randn(24)
rand_vec.min()
rand_vec.max()
rand_vec.mean()
rand_vec.std()
#
print(rand_vec,'\n')
print(rand_vec.size, '\n')
print(rand_vec[9], '\n')
print(rand_vec[18:21],'\n')
print("\nVector elements where Index is from range of numbers\n")
print(rand_vec[np.arange(0,15,3)])
#
# Reshape into 2D array
#
rand_mat=rand_vec.reshape(4,6)
print('')
print(rand_mat,'\n')
print(rand_mat.shape)
print('')
print(rand_mat.size)
print('')
print("1st 2 rows, 4th and 5th column data")
print(rand_mat[0:2,3:5])
print('')
print("Replacing all 2nd column values to zero")
rand_mat[:,1]=0.0
print(rand_mat)
print('')
print("Replacing 3rd row values to 0to5")
rand_mat[2,:]=np.arange(0,6)
print(rand_mat)
#
# Be careful with defining sub-matrices and assigning new values to the sub-matrix elements
# we could alter the original matrix from which the sub-matrix is defined if we don't use copy()
#
sub_mat=rand_mat[0:3,0:3].copy()
sub_mat[:]=23
print('')
print(sub_mat)
print('')
print(rand_mat)

## Indexing logicals

#### Q8a: Retrieve mean, std, var, max, min values from a vector
#### Q8b: Retrieve element(s) of vector based on a condition (logical indexing)
#### Q8c: Modify elements of vector based on conditions
#### Q8d: Do a dot product of 2 vectors


#

In [25]:
#
rand_vec1=np.random.randn(18)

In [26]:
print(rand_vec1)

[-0.09130713  0.39384021 -1.80400378  1.28704169 -1.56816543 -1.55687383
  1.9027148   1.32948179  1.32108987  1.34553142  0.10357921 -1.3858186
 -0.98100338  0.25677362  0.21116757 -0.30604855 -0.92322727 -0.90176239]


In [27]:
rand_vec1.var()

1.3089122092706278

In [28]:
print (rand_vec1)
print('')
print(rand_vec1>0)
print('')
print(rand_vec1[rand_vec1>0])
print('')
print(rand_vec1.mean())

[-0.09130713  0.39384021 -1.80400378  1.28704169 -1.56816543 -1.55687383
  1.9027148   1.32948179  1.32108987  1.34553142  0.10357921 -1.3858186
 -0.98100338  0.25677362  0.21116757 -0.30604855 -0.92322727 -0.90176239]

[False  True False  True False False  True  True  True  True  True False
 False  True  True False False False]

[0.39384021 1.28704169 1.9027148  1.32948179 1.32108987 1.34553142
 0.10357921 0.25677362 0.21116757]

-0.07594389968442733


In [29]:
print(rand_mat)
print('')
print("Transforms matrix to vector")
print(rand_mat[rand_mat<=0])

[[ 0.55129794  0.          0.55759947 -0.6603936   0.49847013  0.23223032]
 [-1.20919335  0.          0.43303327 -0.14498252 -0.79403664  0.16337646]
 [ 0.          1.          2.          3.          4.          5.        ]
 [-0.65637361  0.          0.45668458 -1.07872316 -0.7103887  -0.32289181]]

Transforms matrix to vector
[ 0.         -0.6603936  -1.20919335  0.         -0.14498252 -0.79403664
  0.         -0.65637361  0.         -1.07872316 -0.7103887  -0.32289181]


In [30]:
print(rand_vec1)
rand_vec1[rand_vec1>0.5]= -1.
print('')
print(rand_vec1)

[-0.09130713  0.39384021 -1.80400378  1.28704169 -1.56816543 -1.55687383
  1.9027148   1.32948179  1.32108987  1.34553142  0.10357921 -1.3858186
 -0.98100338  0.25677362  0.21116757 -0.30604855 -0.92322727 -0.90176239]

[-0.09130713  0.39384021 -1.80400378 -1.         -1.56816543 -1.55687383
 -1.         -1.         -1.         -1.          0.10357921 -1.3858186
 -0.98100338  0.25677362  0.21116757 -0.30604855 -0.92322727 -0.90176239]


In [32]:
rand_vec2=np.random.randn(16)
rand_vec2=rand_vec2.reshape(4,4)
print(rand_vec2)
print('')
eye4=np.eye(4)+1
print(eye4)
print('')
print('dot product of two above matrices')
print(np.dot(rand_vec2,eye4))

[[ 0.27359534 -0.42072325  0.10246902 -0.71625009]
 [-1.35856655  1.13729564 -2.07912404 -1.75505329]
 [-0.80122001  0.40784685  0.97196278  0.77310565]
 [-2.33311284  0.71939773  0.59802075 -1.83357148]]

[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]

dot product of two above matrices
[[-0.48731364 -1.18163223 -0.65843996 -1.47715907]
 [-5.41401479 -2.91815261 -6.13457229 -5.81050154]
 [ 0.55047526  1.75954212  2.32365805  2.12480092]
 [-5.18237869 -2.12986811 -2.25124509 -4.68283732]]


## Save and Load Numpy objects into Files

#### Q9a: Save data(s) into a file and then load into zip object and retrieve the data
#### Q9b: Save data into text file and load the txt file 


#

In [33]:
# Save the array data into filename
# Single array = np.save
# multiple arrays = np.savez
np.save('rand_vec_data',rand_vec)
np.savez('arrays_exercise1',rand_vecf=rand_vec,rand_vec1f=rand_vec1)

In [34]:
loaded_vec=np.load('rand_vec_data.npy')
print(loaded_vec)
print('')
loaded_zip=np.load('arrays_exercise1.npz')
print(loaded_zip)
print('')
print(loaded_zip['rand_vecf'])
print('')
print(loaded_zip['rand_vec1f'])

[ 0.55129794  0.          0.55759947 -0.6603936   0.49847013  0.23223032
 -1.20919335  0.          0.43303327 -0.14498252 -0.79403664  0.16337646
  0.          1.          2.          3.          4.          5.
 -0.65637361  0.          0.45668458 -1.07872316 -0.7103887  -0.32289181]


[ 0.55129794  0.          0.55759947 -0.6603936   0.49847013  0.23223032
 -1.20919335  0.          0.43303327 -0.14498252 -0.79403664  0.16337646
  0.          1.          2.          3.          4.          5.
 -0.65637361  0.          0.45668458 -1.07872316 -0.7103887  -0.32289181]

[-0.09130713  0.39384021 -1.80400378 -1.         -1.56816543 -1.55687383
 -1.         -1.         -1.         -1.          0.10357921 -1.3858186
 -0.98100338  0.25677362  0.21116757 -0.30604855 -0.92322727 -0.90176239]


In [35]:
# Save and load files as text files
#
np.savetxt('text_file_rand_mat.txt',rand_mat,delimiter=',')
rand_mat_txt=np.loadtxt('text_file_rand_mat.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[ 0.55129794  0.          0.55759947 -0.6603936   0.49847013  0.23223032]
 [-1.20919335  0.          0.43303327 -0.14498252 -0.79403664  0.16337646]
 [ 0.          1.          2.          3.          4.          5.        ]
 [-0.65637361  0.          0.45668458 -1.07872316 -0.7103887  -0.32289181]]

[[ 0.55129794  0.          0.55759947 -0.6603936   0.49847013  0.23223032]
 [-1.20919335  0.          0.43303327 -0.14498252 -0.79403664  0.16337646]
 [ 0.          1.          2.          3.          4.          5.        ]
 [-0.65637361  0.          0.45668458 -1.07872316 -0.7103887  -0.32289181]]


## Functions

#### Q10a: Define a lambda function to add 3 numbers and get its square root
#### Q10b: Define a function to multiply 4 numbers
#### Q10c: Define a function to split string and retrieve needed


#

In [36]:
# functions lambda
sum_3=lambda x,y,z:np.sqrt(x+y+z)
sum_3(1,3,5)

3.0

In [ ]:
# Same function defined with name
def prod_4(a,b,c,d):
    x=a*b*c*d
    return(x)
product=prod_4(2,4,5,7)
print(product)

In [ ]:
first= lambda x:x.split(', ')[:]
first("Murali Balasubramanian, Great Learning Mentor")

### Practice Question: Use of Lambda function

#### Q11: Generate M positive random real numbers in the range (0,N) for any user defined positive integers M & N?


##### Print output  after Using say 2 sets of values for M and N

#
#### Q12: Take the String "John Taxpayer, +91 9812345678, john.tax@gmail.com" and retrieve the Name, Phone number and email from this text string.

#
#
####  5 min break 
#### + 3 min to generate code


#

In [ ]:
M=20
x=np.absolute(np.random.randn(M))
f=lambda x,num:num*x/max(x)
f(x,100)

In [41]:
# Using numpy function random uniform distribution
x=np.absolute(np.random.uniform(0,100,20))
print(x)

[36.90797976 71.06623926 84.23717382 59.8764713  55.22949107 53.79134803
 98.50658682 23.36304986  5.24432692 79.53948873 63.30971539  4.50727359
 52.64998104 68.92594832 69.73735744 48.62051728 87.82502879 89.56187596
 47.170908   24.73247295]


# Week 2: Pandas - Series and Dataframes

#
#### Q13: Generate a Pandas dataframe from a  list of numbers (1.,4.5,5.6,-2.4,3.1,6.7) or from an array of the list and retrieve a row of the dataframe. Also replace the rows and columns with names

#

In [43]:
# Define a series from a list then rename indices and create dataframe from lists/arrays
#
mylist=[1.,4.5,5.6,-2.4,3.1,6.7]
#
myseries1=pd.Series(data=mylist)
print(myseries1)
#
print('')
print(myseries1[4])
print('')
mylabels=['first','second','third','fourth','fifth','sixth']
myseries3=pd.Series(data=mylist,index=mylabels)
print(myseries3)

0    1.0
1    4.5
2    5.6
3   -2.4
4    3.1
5    6.7
dtype: float64

3.1

first     1.0
second    4.5
third     5.6
fourth   -2.4
fifth     3.1
sixth     6.7
dtype: float64


In [44]:
myarray=np.array(mylist).T
#
print('')
myseries2=pd.Series(data=myarray)
print(myseries2)


0    1.0
1    4.5
2    5.6
3   -2.4
4    3.1
5    6.7
dtype: float64


In [47]:
myseries4=pd.Series([1.,2.5,3.4,-1.6],['1st', '2nd', '3rd','fourth'])
print(myseries4)

1st       1.0
2nd       2.5
3rd       3.4
fourth   -1.6
dtype: float64


####  Q14: Concat of dataframes

In [50]:
df1=pd.concat([myseries3,myseries4],axis=1,sort=False)
print(df1)
#
df3=pd.concat([myseries4,myseries3],axis=0,sort=True)
print('')
print(df3)
#
df2=pd.DataFrame(np.random.randn(5,5))
print('')
print(df2)
print('')
add = pd.DataFrame(np.eye(5))
df4=pd.concat([df2,add], axis=1)
print('\n')
print(df4)

          0    1
first   1.0  NaN
second  4.5  NaN
third   5.6  NaN
fourth -2.4 -1.6
fifth   3.1  NaN
sixth   6.7  NaN
1st     NaN  1.0
2nd     NaN  2.5
3rd     NaN  3.4

1st       1.0
2nd       2.5
3rd       3.4
fourth   -1.6
first     1.0
second    4.5
third     5.6
fourth   -2.4
fifth     3.1
sixth     6.7
dtype: float64

          0         1         2         3         4
0  0.338951 -0.799540 -0.895444  1.646495  0.406843
1 -0.530018 -0.177893 -2.367347  0.205813 -0.046897
2  0.012978  0.433228 -1.532502  0.490650 -1.254033
3 -1.178724  0.970775  0.684310  0.419558 -1.648130
4 -0.528954 -0.579067  0.865700 -0.169245  0.635693



          0         1         2         3         4    0    1    2    3    4
0  0.338951 -0.799540 -0.895444  1.646495  0.406843  1.0  0.0  0.0  0.0  0.0
1 -0.530018 -0.177893 -2.367347  0.205813 -0.046897  0.0  1.0  0.0  0.0  0.0
2  0.012978  0.433228 -1.532502  0.490650 -1.254033  0.0  0.0  1.0  0.0  0.0
3 -1.178724  0.970775  0.684310  0.419558 -1.64813

####  Q15. Use of loc and iloc to retrieve element(s) from dataframe

In [63]:
df4=pd.DataFrame(np.random.randn(4,4),index=['row-1','row-2','row-3','row-4'],columns=['col-1','col-2','col-3','col-4'])
print('')
print(df4)
print('')
print(df4[['col-1','col-3']])
print('')
print(df4.loc['row-2'])
print('')
print('2nd row')
print(df4.iloc[1])
print('')
print('3rd row, 2nd column')
print(df4.iloc[2,1])


          col-1     col-2     col-3     col-4
row-1 -0.809315 -1.451706  0.021357 -0.861915
row-2  0.491819 -1.384655  1.611372 -0.850953
row-3 -2.063312  0.843578  2.030000 -1.004758
row-4  0.785845 -1.300420 -0.550969 -0.908177

          col-1     col-3
row-1 -0.809315  0.021357
row-2  0.491819  1.611372
row-3 -2.063312  2.030000
row-4  0.785845 -0.550969

col-1    0.491819
col-2   -1.384655
col-3    1.611372
col-4   -0.850953
Name: row-2, dtype: float64

2nd row
col-1    0.491819
col-2   -1.384655
col-3    1.611372
col-4   -0.850953
Name: row-2, dtype: float64

3rd row, 2nd column
0.8435784968422051


In [64]:
df4.loc[['row-2','row-3'],['col-2','col-3']]
df4.loc[['row-1','row-3'],['col-4','col-2']]
df4.loc['row-2']
df4.iloc[1:3,1:3]
df4.iloc[2:,2:]

col-2     col-3
row-2 -1.384655  1.611372
row-3  0.843578  2.030000

col-4     col-2
row-1 -0.861915 -1.451706
row-3 -1.004758  0.843578

col-1    0.491819
col-2   -1.384655
col-3    1.611372
col-4   -0.850953
Name: row-2, dtype: float64

col-2     col-3
row-2 -1.384655  1.611372
row-3  0.843578  2.030000

col-3     col-4
row-3  2.030000 -1.004758
row-4 -0.550969 -0.908177

In [65]:
print(df4)

          col-1     col-2     col-3     col-4
row-1 -0.809315 -1.451706  0.021357 -0.861915
row-2  0.491819 -1.384655  1.611372 -0.850953
row-3 -2.063312  0.843578  2.030000 -1.004758
row-4  0.785845 -1.300420 -0.550969 -0.908177


In [66]:
print(df4[df4>0])

          col-1     col-2     col-3  col-4
row-1       NaN       NaN  0.021357    NaN
row-2  0.491819       NaN  1.611372    NaN
row-3       NaN  0.843578  2.030000    NaN
row-4  0.785845       NaN       NaN    NaN


In [67]:
df4['col-5']=np.random.randn(4,1)
df4

col-1     col-2     col-3     col-4     col-5
row-1 -0.809315 -1.451706  0.021357 -0.861915 -1.412035
row-2  0.491819 -1.384655  1.611372 -0.850953  1.788754
row-3 -2.063312  0.843578  2.030000 -1.004758 -1.224097
row-4  0.785845 -1.300420 -0.550969 -0.908177 -1.213719

In [57]:
df4.drop('col-1',axis=1)

col-2     col-3     col-4     col-5
row-1 -1.087305  0.826493 -1.542048  0.686863
row-2 -0.958305 -2.372366 -0.245284  1.176620
row-3  0.517738  1.165906  0.400797  1.040015
row-4 -0.139729  0.850655  0.645052  1.946384

In [68]:
df4.drop('row-3',axis=0, inplace=True)

In [69]:
df4

col-1     col-2     col-3     col-4     col-5
row-1 -0.809315 -1.451706  0.021357 -0.861915 -1.412035
row-2  0.491819 -1.384655  1.611372 -0.850953  1.788754
row-4  0.785845 -1.300420 -0.550969 -0.908177 -1.213719

In [70]:
df4.reset_index()

index     col-1     col-2     col-3     col-4     col-5
0  row-1 -0.809315 -1.451706  0.021357 -0.861915 -1.412035
1  row-2  0.491819 -1.384655  1.611372 -0.850953  1.788754
2  row-4  0.785845 -1.300420 -0.550969 -0.908177 -1.213719

In [71]:
df4

col-1     col-2     col-3     col-4     col-5
row-1 -0.809315 -1.451706  0.021357 -0.861915 -1.412035
row-2  0.491819 -1.384655  1.611372 -0.850953  1.788754
row-4  0.785845 -1.300420 -0.550969 -0.908177 -1.213719

In [72]:
df4.reset_index(inplace=True)

In [73]:
df4

index     col-1     col-2     col-3     col-4     col-5
0  row-1 -0.809315 -1.451706  0.021357 -0.861915 -1.412035
1  row-2  0.491819 -1.384655  1.611372 -0.850953  1.788754
2  row-4  0.785845 -1.300420 -0.550969 -0.908177 -1.213719

In [74]:
df4['col-6']=df4['col-5']+df4['col-4']
df4

index     col-1     col-2     col-3     col-4     col-5     col-6
0  row-1 -0.809315 -1.451706  0.021357 -0.861915 -1.412035 -2.273949
1  row-2  0.491819 -1.384655  1.611372 -0.850953  1.788754  0.937801
2  row-4  0.785845 -1.300420 -0.550969 -0.908177 -1.213719 -2.121896

In [ ]:
# Write code line for creating New name

In [ ]:
df4.set_index('new name',inplace=True)
df4

In [76]:
df4.mean()

col-1    0.156116
col-2   -1.378927
col-3    0.360587
col-4   -0.873682
col-5   -0.279000
col-6   -1.152681
dtype: float64

In [ ]:
data={'prodID':['101','102','103','104','104'], 
      'prodname':['X','Y','Z','X','W'],
                  'profit':['2738','2727','3497','7347','3743']}
dataframe=pd.DataFrame(data)
dataframe
grouped_data=dataframe.groupby('prodID')
grouped_data.max()

## Concatenating, Merging and Joining DataFrames

In [77]:
#
df7 = pd.DataFrame({"customer":['101','102','103','104'], 
                    'category': ['cat2','cat2','cat1','cat3'],
                    'important': ['yes','no','yes','yes'],
                    'sales': [123,52,214,663]},index=[0,1,2,3])

df8 = pd.DataFrame({"customer":['101','103','104','105'], 
                    'color': ['yellow','green','green','blue'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [78]:
df7

customer category important  sales
0      101     cat2       yes    123
1      102     cat2        no     52
2      103     cat1       yes    214
3      104     cat3       yes    663

In [79]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [80]:
pd.concat([df7,df8],axis=0,sort=False)

customer category important  sales   color  distance
0      101     cat2       yes    123     NaN       NaN
1      102     cat2        no     52     NaN       NaN
2      103     cat1       yes    214     NaN       NaN
3      104     cat3       yes    663     NaN       NaN
4      101      NaN       NaN    123  yellow      12.0
5      103      NaN       NaN    214   green       9.0
6      104      NaN       NaN    663   green      44.0
7      105      NaN       NaN    331    blue      21.0

In [81]:
pd.concat([df7,df8],axis=0,sort=True)

category   color customer  distance important  sales
0     cat2     NaN      101       NaN       yes    123
1     cat2     NaN      102       NaN        no     52
2     cat1     NaN      103       NaN       yes    214
3     cat3     NaN      104       NaN       yes    663
4      NaN  yellow      101      12.0       NaN    123
5      NaN   green      103       9.0       NaN    214
6      NaN   green      104      44.0       NaN    663
7      NaN    blue      105      21.0       NaN    331

In [82]:
pd.concat([df7,df8],axis=1,sort=False)

customer category important  sales customer   color  distance  sales
0      101     cat2       yes  123.0      NaN     NaN       NaN    NaN
1      102     cat2        no   52.0      NaN     NaN       NaN    NaN
2      103     cat1       yes  214.0      NaN     NaN       NaN    NaN
3      104     cat3       yes  663.0      NaN     NaN       NaN    NaN
4      NaN      NaN       NaN    NaN      101  yellow      12.0  123.0
5      NaN      NaN       NaN    NaN      103   green       9.0  214.0
6      NaN      NaN       NaN    NaN      104   green      44.0  663.0
7      NaN      NaN       NaN    NaN      105    blue      21.0  331.0

In [83]:
pd.merge(df7,df8,how='outer',on='customer') # outer merge is union of on

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow      12.0    123.0
1      102     cat2        no     52.0     NaN       NaN      NaN
2      103     cat1       yes    214.0   green       9.0    214.0
3      104     cat3       yes    663.0   green      44.0    663.0
4      105      NaN       NaN      NaN    blue      21.0    331.0

In [84]:
pd.merge(df7,df8,how='inner',on='customer') # inner merge is intersection of on

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow        12      123
1      103     cat1       yes      214   green         9      214
2      104     cat3       yes      663   green        44      663

In [85]:
pd.merge(df7,df8,how='left',on='customer') # left merge is just first on, but all columns ... left is just first df

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes      123  yellow      12.0    123.0
1      102     cat2        no       52     NaN       NaN      NaN
2      103     cat1       yes      214   green       9.0    214.0
3      104     cat3       yes      663   green      44.0    663.0

In [86]:
pd.merge(df7,df8,how='right',on='customer') # right merge is just first on, but all columns ... right is second df

customer category important  sales_x   color  distance  sales_y
0      101     cat2       yes    123.0  yellow        12      123
1      103     cat1       yes    214.0   green         9      214
2      104     cat3       yes    663.0   green        44      663
3      105      NaN       NaN      NaN    blue        21      331

In [87]:
df9 = pd.DataFrame({'Q1': [101,102,103],
                    'Q2': [201,202,203]},
                   index=['I0','I1','I2'])

df10 = pd.DataFrame({'Q3': [301,302,303],
                    'Q4': [401,402,403]},
                   index=['I0','I2','I3'])

In [88]:
df9

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [89]:
df10

Q3   Q4
I0  301  401
I2  302  402
I3  303  403

In [90]:
# join behaves just like merge, 
# except instead of using the values of one of the columns 
# to combine data frames, it uses the index labels
df9.join(df10,how='outer') # outer, inner, left, and right work the same as merge

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2  103.0  203.0  302.0  402.0
I3    NaN    NaN  303.0  403.0

In [ ]:
df9.join(df10,how='inner')

In [96]:
pd.concat([df9,df10],axis=1,sort=True)

Q1     Q2     Q3     Q4
I0  101.0  201.0  301.0  401.0
I1  102.0  202.0    NaN    NaN
I2  103.0  203.0  302.0  402.0
I3    NaN    NaN  303.0  403.0

In [95]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [99]:
df8['color'].unique()

array(['yellow', 'green', 'blue'], dtype=object)

In [101]:
df8['color'].value_counts(normalize=True)

green     0.50
yellow    0.25
blue      0.25
Name: color, dtype: float64

In [102]:
df9.mean()

Q1    102.0
Q2    202.0
dtype: float64

In [103]:
df8.columns

Index(['customer', 'color', 'distance', 'sales'], dtype='object')

In [104]:
df8

customer   color  distance  sales
4      101  yellow        12    123
5      103   green         9    214
6      104   green        44    663
7      105    blue        21    331

In [105]:
new_df=df8[(df8['customer']!='105')&(df8['color']!='green')]
new_df

customer   color  distance  sales
4      101  yellow        12    123

In [106]:
print(df8['sales'].mean())
print(df8['distance'].min())

332.75
9


In [107]:
def profit(s):
    return s*0.5 # 50% markup...

In [113]:
def loss(s):
    return(s*0.05)

In [114]:
df8['sales'].apply(loss)

4     6.15
5    10.70
6    33.15
7    16.55
Name: sales, dtype: float64

In [109]:
df8['profit']=df8['sales'].apply(profit)

In [110]:
df8

customer   color  distance  sales  profit
4      101  yellow        12    123    61.5
5      103   green         9    214   107.0
6      104   green        44    663   331.5
7      105    blue        21    331   165.5

In [111]:
df8['color'].apply(len)

4    6
5    5
6    5
7    4
Name: color, dtype: int64

In [116]:
df11 = df8[['distance','sales']]
df11

distance  sales
4        12    123
5         9    214
6        44    663
7        21    331

In [117]:

df11.applymap(profit)

distance  sales
4       6.0   61.5
5       4.5  107.0
6      22.0  331.5
7      10.5  165.5

In [118]:
def col_sum(co):
    return sum(co)
df11.apply(col_sum)

distance      86
sales       1331
dtype: int64

In [ ]:
df11.applymap(col_sum)
# This is wrong since applymap is for global elements of dframe

In [120]:
del df8['color']
df8

customer  distance  sales  profit
4      101        12    123    61.5
5      103         9    214   107.0
6      104        44    663   331.5
7      105        21    331   165.5

In [121]:
df8.index

Int64Index([4, 5, 6, 7], dtype='int64')

In [122]:
df8.sort_values(by='distance',inplace=True)
df8

customer  distance  sales  profit
5      103         9    214   107.0
4      101        12    123    61.5
7      105        21    331   165.5
6      104        44    663   331.5

In [ ]:
# if some series has multiple of the same value then we can group all the unique entries together
mydict = {'customer': ['Customer 1','Customer 1','Customer2','Customer2','Customer3','Customer3'], 
          'product1': [1.1,2.1,3.8,4.2,5.5,6.9],
          'product2': [8.2,9.1,11.1,5.2,44.66,983]}
df6 = pd.DataFrame(mydict,index=['Purchase 1','Purchase 2','Purchase 3','Purchase 4','Purchase 5','Purchase 6'])
df6

In [ ]:
grouped_data = df6.groupby('customer')
print(grouped_data)

In [ ]:
grouped_data.mean()

In [ ]:
df8

In [ ]:
# similar to numpy arrays, we can also save and load dataframes to csv files, and also Excel files

df8.to_csv('df8.csv',index=True)

In [ ]:
new_df8 = pd.read_csv('df8.csv',index_col=0)
new_df8

In [ ]:
df8.to_excel('df8.xlsx',index=False,sheet_name='first sheet')
newer_df8 = pd.read_excel('df8.xlsx',sheet_name='first sheet',index_col=0)
newer_df8

### Week 1.1 CASE STUDY - ONLINE GAMES

* Data has various online boardgames and metadata associated with it to analyze
* There's game attributes and user feedback as part of the dataset

In [125]:
games_df=pd.read_csv('games.csv')
print("Shape of games_df: ",games_df.shape, "Size of games_df: ", games_df.size, '\n')
# Print the 1st 5 rows of the dataframe


Shape of games_df:  (81312, 20) Size of games_df:  1626240 



In [127]:
games_df.head()

id       type                                       name  \
0   12333  boardgame                          Twilight Struggle   
1  120677  boardgame                              Terra Mystica   
2  102794  boardgame                  Caverna: The Cave Farmers   
3   25613  boardgame  Through the Ages: A Story of Civilization   
4    3076  boardgame                                Puerto Rico   

   yearpublished  minplayers  maxplayers  playingtime  minplaytime  \
0         2005.0         2.0         2.0        180.0        180.0   
1         2012.0         2.0         5.0        150.0         60.0   
2         2013.0         1.0         7.0        210.0         30.0   
3         2006.0         2.0         4.0        240.0        240.0   
4         2002.0         2.0         5.0        150.0         90.0   

   maxplaytime  minage  users_rated  average_rating  bayes_average_rating  \
0        180.0    13.0        20113         8.33774               8.22186   
1        150.0    12.0        14383         8.28798               8.14232   
2        210.0    12.0         9262         8.28994               8.06886   
3        240.0    12.0        13294         8.20407               8.05804   
4        150.0    12.0        39883         8.14261               8.04524   

   total_owners  total_traders  total_wanters  total_wishers  total_comments  \
0         26647            372           1219           5865            5347   
1         16519            132           1586           6277            2526   
2         12230             99           1476           5600            1700   
3         14343            362           1084           5075            3378   
4         44362            795            861           5414            9173   

   total_weights  average_weight  
0           2562          3.4785  
1           1423          3.8939  
2            777          3.7761  
3           1642          4.1590  
4           5213          3.2943

In [128]:
# Info on dataframe in terms of datatype and # of records(rows)
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81312 entries, 0 to 81311
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    81312 non-null  int64  
 1   type                  81312 non-null  object 
 2   name                  81271 non-null  object 
 3   yearpublished         81309 non-null  float64
 4   minplayers            81309 non-null  float64
 5   maxplayers            81309 non-null  float64
 6   playingtime           81309 non-null  float64
 7   minplaytime           81309 non-null  float64
 8   maxplaytime           81309 non-null  float64
 9   minage                81309 non-null  float64
 10  users_rated           81312 non-null  int64  
 11  average_rating        81312 non-null  float64
 12  bayes_average_rating  81312 non-null  float64
 13  total_owners          81312 non-null  int64  
 14  total_traders         81312 non-null  int64  
 15  total_wanters      

In [129]:
# Sort the games by yearpublished in ascending sequence
games_df.sort_values(by='yearpublished',inplace=True)

In [134]:
games_df.head(50)

id       type                                           name  \
6284     2399  boardgame                                          Senet   
28268   23211  boardgame                                     20 Squares   
2717     2397  boardgame                                     Backgammon   
12908    5546  boardgame                                        Marbles   
19077   11726  boardgame                                   Knucklebones   
917      2397  boardgame                                     Backgammon   
42209   39628  boardgame                                         Jiroft   
11841    1602  boardgame                           The Royal Game of Ur   
70        188  boardgame                                             Go   
1870      188  boardgame                                             Go   
13701    2912  boardgame       Hounds and Jackals: Game of the Pharaohs   
14232    4148  boardgame                                          Mehen   
40594   37701  boardgame                                    Five Stones   
32341   28128  boardgame                                        Pah Tum   
12189   19915  boardgame                             Three Men's Morris   
12718    3886  boardgame                              Nine Men's Morris   
30299   25702  boardgame                               Six Men's Morris   
80017  180952  boardgame                             Seven Men's Morris   
13034   11901  boardgame                                    Tic-Tac-Toe   
27762   22610  boardgame                                          Liubo   
42908   40412  boardgame                                        Fan Tan   
20645   13776  boardgame                                      Ashtapada   
13033    5432  boardgame                             Snakes and Ladders   
26869   21488  boardgame                                        Petteia   
28815   23868  boardgame                                          Trezo   
28817   23871  boardgame                                  Daruma Otoshi   
28822   23879  boardgame                                        Sacoma!   
28927   24023  boardgame                     The Game of Midlothian, VA   
28923   24019  boardgame                                        Strike!   
28907   23996  boardgame                                      LifeCards   
28897   23983  boardgame                                  Finger Soccer   
28829   23887  boardgame                                     Rage! Game   
28831   23889  boardgame                                       Stack'em   
28844   23906  boardgame                                      Cry Wolf!   
28885   23966  boardgame  Science Fusion, the Elements of the Scienauts   
28851   23918  boardgame                                   First Strike   
28855   23924  boardgame                                 Stock Exchange   
28879   23955  boardgame                                Truffle Shuffle   
25930   20328  boardgame                                      I.U.opoly   
28773   23819  boardgame                  Chalk Talk Hockey Trivia Game   
28787   23838  boardgame                        Complete Tiddledy Winks   
28614   23624  boardgame                                Spread the Word   
28619   23629  boardgame                          les Prodiges du sport   
28626   23637  boardgame                                Spice Merchants   
28627   23638  boardgame                        WWF Taktinen Luontopeli   
28628   23639  boardgame                                    Marble Bowl   
28664   23690  boardgame                   Ice Frenzie Hockey Card Game   
28680   23711  boardgame                                    Fridgeracer   
28688   23720  boardgame                                  Family Jewels   
28702   23736  boardgame                            Missionary Conquest   

       yearpublished  minplayers  maxplayers  playingtime  minplaytime  \
6284         -3500.0         2.0         2.0         30.0         30.0   
28268        -3000.0         2.0     

In [137]:
games_df.yearpublished.unique()

array([-3500., -3000., -2500., -2200., -2000., -1800., -1400., -1300.,
        -700.,  -600.,  -350.,  -200.,  -100.,     0.,   220.,   300.,
         400.,   500.,   550.,   600.,   650.,   700.,   762.,   800.,
         900.,  1000.,  1100.,  1120.,  1125.,  1150.,  1200.,  1202.,
        1227.,  1230.,  1283.,  1300.,  1350.,  1370.,  1375.,  1400.,
        1425.,  1426.,  1430.,  1441.,  1450.,  1457.,  1475.,  1490.,
        1500.,  1522.,  1530.,  1534.,  1550.,  1575.,  1578.,  1579.,
        1586.,  1587.,  1588.,  1589.,  1600.,  1601.,  1611.,  1617.,
        1630.,  1636.,  1645.,  1650.,  1660.,  1661.,  1662.,  1663.,
        1674.,  1680.,  1683.,  1687.,  1690.,  1695.,  1697.,  1700.,
        1701.,  1715.,  1717.,  1719.,  1720.,  1726.,  1730.,  1740.,
        1741.,  1742.,  1745.,  1747.,  1750.,  1759.,  1760.,  1762.,
        1766.,  1768.,  1770.,  1774.,  1775.,  1778.,  1780.,  1783.,
        1784.,  1785.,  1787.,  1790.,  1791.,  1793.,  1794.,  1795.,
      

In [ ]:
games_df.tail(5)

In [138]:
games_df['type'].value_counts()

boardgame             70820
boardgameexpansion    10492
Name: type, dtype: int64

In [139]:
print(games_df.yearpublished,'\n')
X=np.array(games_df.yearpublished);
print('\n',X)

6284    -3500.0
28268   -3000.0
2717    -3000.0
12908   -3000.0
19077   -3000.0
          ...  
80092    2018.0
79942    2018.0
45972       NaN
46057       NaN
46537       NaN
Name: yearpublished, Length: 81312, dtype: float64 


 [-3500. -3000. -3000. ...    nan    nan    nan]


In [140]:
# find the game(s) with max playing time amongst all games
print(games_df['playingtime'].max(),'\n')
games_df[games_df['playingtime']==games_df['playingtime'].max()]

60120.0 



id       type                             name  yearpublished  \
74055  164363  boardgame  Hammer's Slammers: The Crucible         2010.0   

       minplayers  maxplayers  playingtime  minplaytime  maxplaytime  minage  \
74055         2.0         4.0      60120.0      60120.0      60120.0    14.0   

       users_rated  average_rating  bayes_average_rating  total_owners  \
74055            1             7.5                   0.0             4   

       total_traders  total_wanters  total_wishers  total_comments  \
74055              0              0              0               0   

       total_weights  average_weight  
74055              0             0.0

In [141]:
# What is the mean playing time for all games put together
games_df['playingtime'].mean()

51.63478827682052

In [142]:
# find the games with max and min total comments
games_df[games_df['total_comments']==games_df['total_comments'].max()]
games_df[games_df['total_comments']==games_df['total_comments'].min()]

id       type   name  yearpublished  minplayers  maxplayers  \
1965  13  boardgame  Catan         1995.0         3.0         4.0   
165   13  boardgame  Catan         1995.0         3.0         4.0   

      playingtime  minplaytime  maxplaytime  minage  users_rated  \
1965         90.0         90.0         90.0    10.0        53680   
165          90.0         90.0         90.0    10.0        53680   

      average_rating  bayes_average_rating  total_owners  total_traders  \
1965         7.34303               7.21171         73188           1071   
165          7.34303               7.21171         73188           1071   

      total_wanters  total_wishers  total_comments  total_weights  \
1965            391           3201           11798           5996   
165             391           3201           11798           5996   

      average_weight  
1965          2.3712  
165           2.3712

id       type                                    name  \
28268   23211  boardgame                              20 Squares   
42209   39628  boardgame                                  Jiroft   
80017  180952  boardgame                      Seven Men's Morris   
42908   40412  boardgame                                 Fan Tan   
28927   24023  boardgame              The Game of Midlothian, VA   
...       ...        ...                                     ...   
80677  182409  boardgame                        Midway Solitaire   
81294  184349  boardgame                The Luzon Campaign, 1945   
80092  181140  boardgame                               Soyuz '81   
79942  180797  boardgame  The ISIS War: The Next Middle East War   
45972   53344  boardgame                    Kirby the Board Game   

       yearpublished  minplayers  maxplayers  playingtime  minplaytime  \
28268        -3000.0         2.0         2.0         30.0         30.0   
42209        -2500.0         0.0         0.0          0.0          0.0   
80017        -1400.0         2.0         2.0          0.0          0.0   
42908         -600.0         3.0         8.0          5.0          5.0   
28927            0.0         2.0         6.0        120.0        120.0   
...              ...         ...         ...          ...          ...   
80677         2017.0         2.0         2.0          0.0          0.0   
81294         2018.0         1.0         1.0          0.0          0.0   
80092         2018.0         1.0         2.0          0.0          0.0   
79942         2018.0         2.0         2.0          0.0          0.0   
45972            NaN         NaN         NaN          NaN          NaN   

       maxplaytime  minage  users_rated  average_rating  bayes_average_rating  \
28268         30.0    10.0            1             3.0                   0.0   
42209          0.0     0.0            0             0.0                   0.0   
80017          0.0     8.0            1             7.0                   0.0   
42908          5.0     0.0            0             0.0                   0.0   
28927        120.0     0.0            0             0.0                   0.0   
...            ...     ...          ...             ...                   ...   
80677          0.0     0.0            0             0.0                   0.0   
81294          0.0     0.0            0             0.0                   0.0   
80092          0.0     0.0            0             0.0                   0.0   
79942          0.0     0.0            0             0.0                   0.0   
45972          NaN     NaN            0             0.0                   0.0   

       total_owners  total_traders  total_wanters  total_wishers  \
28268             0              0              0              1   
42209             0              0              1              2   
80017             1              0              0              0   
42908             0              0              0              0   
28927             1              0              0              0   
...             ...            ...            ...            ...   
80677             0              0              0              0   
81294             0              0              0              0   
80092             0              0              0              0   
79942             0              0              1              3   
45972             2              0              0              3   

       total_comments  total_weights  average_weight  
28268               0              0             0.0  
42209               0              0             0.0  
80017               0              0             0.0  
42908               0              0             0.0  
28927               0              0             0.0  
...               ...            ...             ...  
80677               0              0             0.0  
81294               0              0             0.0  
80092               

In [ ]:
# use .duplicate()

In [144]:
# What game has id 1500
games_df[games_df['id']==1500]['name']
games_df[games_df['id']==1500]

10592    Zocken
Name: name, dtype: object

id       type    name  yearpublished  minplayers  maxplayers  \
10592  1500  boardgame  Zocken         1999.0         2.0         8.0   

       playingtime  minplaytime  maxplaytime  minage  users_rated  \
10592         30.0         30.0         30.0     8.0           38   

       average_rating  bayes_average_rating  total_owners  total_traders  \
10592         5.60184               5.50547            62              4   

       total_wanters  total_wishers  total_comments  total_weights  \
10592              0              4              13              6   

       average_weight  
10592          1.1667

In [145]:
# What is the average minage and bayes_average_rating of all games per game "type"? (boardgame & boardgameexpansion)
games_df.groupby('type').mean()['minage']

type
boardgame             6.724798
boardgameexpansion    8.733321
Name: minage, dtype: float64

In [146]:
games_df.groupby('type').mean()['bayes_average_rating']

type
boardgame             1.083140
boardgameexpansion    1.660447
Name: bayes_average_rating, dtype: float64

In [147]:
#How many boardgames and boardgameexpansions are there in the dataset?
games_df['type'].value_counts()

boardgame             70820
boardgameexpansion    10492
Name: type, dtype: int64

In [ ]:
# Is there a correlation between playing time and total comments for the games? - Use the .corr() function 
games_df[['playingtime','total_comments']].corr() 
# No correlation.

In [ ]:
#View the distance plot for average rating for each game
sns.displot(games_df['average_rating'], kde='True');

In [ ]:
#Compare type of game and playingtime using  a stripplot
sns.stripplot(x=games_df['type'], y=games_df['playingtime'], jitter= True);

### CASE STUDY Week 1.2-  WEEKLY TRACKER  FOR TIME & DATE OBJECTS

* The data is a weekly tracker of activity of a working manager by a daily   
  scheduler / tracker app 
* We will try and read the timestamp and convert to analyzable time data
* We will look at the activity specific metrics in terms of weekly timespent
* Basic Exploratory Data Analysis (non-visual) is first used to study the data 
  and glean useful information

In [148]:
path = 'C:/Users/MuraliSAI/Documents/AIML_working_folder'

In [149]:
# Get the Data 
df1 = pd.read_csv(path+'/'+'Weekly_schedule_tracker_detail1.csv')
df1.head(50)

START_TIME          END_TIME             CATEGORY  \
0    4/17/2023 06:02  4/17/2023  06:26            ABLUTIONS   
1    4/17/2023 06:30  4/17/2023  07:30   HEALTH and FITNESS   
2   4/17/2023  07:35  4/17/2023  07:56            ABLUTIONS   
3   4/17/2023  08:04  4/17/2023  08:26                MEALS   
4    4/17/2023 08:32  4/17/2023  08:58  ONLINE INFOTAINMENT   
5   4/17/2023  09:00  4/17/2023  11:00             BUSINESS   
6   4/17/2023  11:02  4/17/2023  11:07                MEALS   
7    4/17/2023 11:08  4/17/2023  11:30  ONLINE INFOTAINMENT   
8    4/17/2023 11:32  4/17/2023  13:05             BUSINESS   
9    4/17/2023 13:05  4/17/2023  13:35                MEALS   
10   4/17/2023 13:36  4/17/2023  13:58  ONLINE INFOTAINMENT   
11   4/17/2023 14:02  4/17/2023  15:33             BUSINESS   
12   4/17/2023 15:34  4/17/2023  16:00                MEALS   
13   4/17/2023 16:01  4/17/2023  17:40             BUSINESS   
14   4/17/2023 17:40  4/17/2023  18:00  ONLINE INFOTAINMENT   
15   4/17/2023 18:02  4/17/2023  18:35   HEALTH and FITNESS   
16   4/17/2023 18:40  4/17/2023  19:02            ABLUTIONS   
17   4/17/2023 19:03  4/17/2023  20:00             BUSINESS   
18   4/17/2023 20:05  4/17/2023  20:35                MEALS   
19   4/17/2023 20:45  4/17/2023  22:40  ONLINE INFOTAINMENT   
20   4/18/2023 06:05   4/18/2023 06:25            ABLUTIONS   
21   4/18/2023 06:30   4/18/2023 07:29   HEALTH and FITNESS   
22   4/18/2023 07:35   4/18/2023 07:55            ABLUTIONS   
23   4/18/2023 08:03   4/18/2023 08:24                MEALS   
24   4/18/2023 08:30   4/18/2023 08:55  ONLINE INFOTAINMENT   
25   4/18/2023 09:00   4/18/2023 11:02             BUSINESS   
26   4/18/2023 11:03   4/18/2023 11:08                MEALS   
27   4/18/2023 11:10   4/18/2023 11:30  ONLINE INFOTAINMENT   
28   4/18/2023 11:34   4/18/2023 13:05             BUSINESS   
29   4/18/2023 13:05   4/18/2023 13:28                MEALS   
30   4/18/2023 13:30   4/18/2023 14:05             BUSINESS   
31   4/18/2023 14:05   4/18/2023 15:31             BUSINESS   
32   4/18/2023 15:32   4/18/2023 16:00                MEALS   
33   4/18/2023 16:00   4/18/2023 17:58             BUSINESS   
34   4/18/2023 18:00   4/18/2023 18:22  ONLINE INFOTAINMENT   
35   4/18/2023 18:30   4/18/2023 19:05   HEALTH and FITNESS   
36   4/18/2023 19:10   4/18/2023 19:29            ABLUTIONS   
37   4/18/2023 19:35   4/18/2023 20:05                MEALS   
38   4/18/2023 20:05   4/18/2023 22:15           RELAXATION   
39   4/18/2023 22:15   4/18/2023 22:35  ONLINE INFOTAINMENT   
40   4/19/2023 06:01   4/19/2023 06:20            ABLUTIONS   
41   4/19/2023 06:27   4/19/2023 07:30   HEALTH and FITNESS   
42   4/19/2023 07:35   4/19/2023 07:55            ABLUTIONS   
43   4/19/2023 08:05   4/19/2023 08:24                MEALS   
44   4/19/2023 08:30   4/19/2023 08:55  ONLINE INFOTAINMENT   
45   4/19/2023 09:00   4/19/2023 11:02             BUSINESS   
46   4/19/2023 11:05   4/19/2023 11:10                MEALS   
47   4/19/2023 11:10   4/19/2023 11:31  ONLINE INFOTAINMENT   
48   4/19/2023 11:33   4/19/2023 13:05             BUSINESS   
49   4/19/2023 13:05   4/19/2023 13:35                MEALS   

                              ACTIVITY  
0                   WAKE UP AND WASHUP  
1                                YOGA   
2                         MORNING BATH  
3                            BREAKFAST  
4              NEWS and SOCIAL NETWORK  
5                    WORK AND MEETINGS  
6                         COFFEE BREAK  
7              NEWS and SOCIAL NETWORK  
8                    WORK AND MEETINGS  
9                                LUNCH  
10             NEWS and SOCIAL NETWORK  
11                   WORK AND MEETINGS  
12                           TEA BREAK  
13                   WORK AND MEETINGS  
14             NEWS and SOCIAL NETWORK  
15                         EVENING RUN  
16                        EVENING BATH  
17                     VIRTUAL MEETING  
18               

In [150]:
df2 = pd.read_csv(path+'/'+'Weekly_schedule_tracker_detail2.csv')
df2.head()

START_TIME          END_TIME                   LOCATION
0   4/17/2023 06:02  4/17/2023  06:26                       HOME
1   4/17/2023 06:30  4/17/2023  07:30                YOGA CENTER
2  4/17/2023  07:35  4/17/2023  07:56                       HOME
3  4/17/2023  08:04  4/17/2023  08:26                       HOME
4   4/17/2023 08:32  4/17/2023  08:58  ON ROAD BY CHAUFFERED CAR

In [151]:
df=pd.merge(df1,df2,how='inner', on=['START_TIME','END_TIME']) # outer merge is union 

In [152]:
df.head()

START_TIME          END_TIME             CATEGORY  \
0   4/17/2023 06:02  4/17/2023  06:26            ABLUTIONS   
1   4/17/2023 06:30  4/17/2023  07:30   HEALTH and FITNESS   
2  4/17/2023  07:35  4/17/2023  07:56            ABLUTIONS   
3  4/17/2023  08:04  4/17/2023  08:26                MEALS   
4   4/17/2023 08:32  4/17/2023  08:58  ONLINE INFOTAINMENT   

                  ACTIVITY                   LOCATION  
0       WAKE UP AND WASHUP                       HOME  
1                    YOGA                 YOGA CENTER  
2             MORNING BATH                       HOME  
3                BREAKFAST                       HOME  
4  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR

In [153]:
df.shape

(127, 5)

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127 entries, 0 to 126
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   START_TIME  127 non-null    object
 1   END_TIME    127 non-null    object
 2   CATEGORY    127 non-null    object
 3   ACTIVITY    127 non-null    object
 4   LOCATION    127 non-null    object
dtypes: object(5)
memory usage: 6.0+ KB


In [1]:
df.describe()

NameError: name 'df' is not defined

In [ ]:
df.CATEGORY.value_counts()

MEALS                  33
ONLINE INFOTAINMENT    25
BUSINESS               23
ABLUTIONS              20
HEALTH and FITNESS     13
RELAXATION              4
TRAVEL                  3
ENTERTAINMENT           2
HOME MAINTENANCE        2
TEACHING                1
SHOPPING                1
Name: CATEGORY, dtype: int64

In [157]:
df.ACTIVITY.unique()

array(['WAKE UP AND WASHUP', 'YOGA ', 'MORNING BATH', 'BREAKFAST',
       'NEWS and SOCIAL NETWORK', 'WORK AND MEETINGS', 'COFFEE BREAK',
       'LUNCH', 'TEA BREAK', 'EVENING RUN', 'EVENING BATH',
       'VIRTUAL MEETING', 'DINNER', 'WATCH IPL MATCH', 'MEETING', 'GYM',
       'RELAXED FAMILY TIME', 'SOCIAL NETWORK and PERSONAL EMAILS',
       'MUSIC CONCERT', 'DRIVING', 'VIRTUAL CLASSROOM',
       'GROCERIES AND PRODUCE', 'NAP', 'FAMILY CONCALL', 'CLEANING',
       'EVENING RUN AND GYM', 'BOARDGAME WITH FAMILY',
       'CLEANING AND FINANCE BOOK KEEPING', 'MOVIE WITH FAMILY'],
      dtype=object)

In [158]:
df['START_TIME']=pd.to_datetime(df['START_TIME'])

In [159]:
df['END_TIME']=pd.to_datetime(df['END_TIME'])

In [160]:
df.head(10)

START_TIME            END_TIME             CATEGORY  \
0 2023-04-17 06:02:00 2023-04-17 06:26:00            ABLUTIONS   
1 2023-04-17 06:30:00 2023-04-17 07:30:00   HEALTH and FITNESS   
2 2023-04-17 07:35:00 2023-04-17 07:56:00            ABLUTIONS   
3 2023-04-17 08:04:00 2023-04-17 08:26:00                MEALS   
4 2023-04-17 08:32:00 2023-04-17 08:58:00  ONLINE INFOTAINMENT   
5 2023-04-17 09:00:00 2023-04-17 11:00:00             BUSINESS   
6 2023-04-17 11:02:00 2023-04-17 11:07:00                MEALS   
7 2023-04-17 11:08:00 2023-04-17 11:30:00  ONLINE INFOTAINMENT   
8 2023-04-17 11:32:00 2023-04-17 13:05:00             BUSINESS   
9 2023-04-17 13:05:00 2023-04-17 13:35:00                MEALS   

                  ACTIVITY                   LOCATION  
0       WAKE UP AND WASHUP                       HOME  
1                    YOGA                 YOGA CENTER  
2             MORNING BATH                       HOME  
3                BREAKFAST                       HOME  
4  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR  
5        WORK AND MEETINGS                    OFFICE1  
6             COFFEE BREAK         OFFICE1 CAFFETERIA  
7  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR  
8        WORK AND MEETINGS                    OFFICE2  
9                    LUNCH         OFFICE2 CAFFETERIA

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127 entries, 0 to 126
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   START_TIME  127 non-null    datetime64[ns]
 1   END_TIME    127 non-null    datetime64[ns]
 2   CATEGORY    127 non-null    object        
 3   ACTIVITY    127 non-null    object        
 4   LOCATION    127 non-null    object        
dtypes: datetime64[ns](2), object(3)
memory usage: 6.0+ KB


In [162]:
df['time_elapsed']=df['END_TIME']-df['START_TIME']

In [163]:
df.head(10)

START_TIME            END_TIME             CATEGORY  \
0 2023-04-17 06:02:00 2023-04-17 06:26:00            ABLUTIONS   
1 2023-04-17 06:30:00 2023-04-17 07:30:00   HEALTH and FITNESS   
2 2023-04-17 07:35:00 2023-04-17 07:56:00            ABLUTIONS   
3 2023-04-17 08:04:00 2023-04-17 08:26:00                MEALS   
4 2023-04-17 08:32:00 2023-04-17 08:58:00  ONLINE INFOTAINMENT   
5 2023-04-17 09:00:00 2023-04-17 11:00:00             BUSINESS   
6 2023-04-17 11:02:00 2023-04-17 11:07:00                MEALS   
7 2023-04-17 11:08:00 2023-04-17 11:30:00  ONLINE INFOTAINMENT   
8 2023-04-17 11:32:00 2023-04-17 13:05:00             BUSINESS   
9 2023-04-17 13:05:00 2023-04-17 13:35:00                MEALS   

                  ACTIVITY                   LOCATION    time_elapsed  
0       WAKE UP AND WASHUP                       HOME 0 days 00:24:00  
1                    YOGA                 YOGA CENTER 0 days 01:00:00  
2             MORNING BATH                       HOME 0 days 00:21:00  
3                BREAKFAST                       HOME 0 days 00:22:00  
4  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR 0 days 00:26:00  
5        WORK AND MEETINGS                    OFFICE1 0 days 02:00:00  
6             COFFEE BREAK         OFFICE1 CAFFETERIA 0 days 00:05:00  
7  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR 0 days 00:22:00  
8        WORK AND MEETINGS                    OFFICE2 0 days 01:33:00  
9                    LUNCH         OFFICE2 CAFFETERIA 0 days 00:30:00

In [ ]:
df.info()

In [ ]:
# Alternate method to convert string to date time in specified format
#df.loc[:, 'START_TIME'] = df['START_TIME'].apply(lambda x: pd.datetime.strptime(x, '%m/%d/%Y %H:%M'))
#df.loc[:, 'END_TIME'] = df['END_TIME'].apply(lambda x: pd.datetime.strptime(x, '%m/%d/%Y %H:%M'))

In [164]:
#convert duration to numbers(minutes)
df.loc[:, 'time_elapsed'] = df['time_elapsed'].apply(lambda x: pd.Timedelta.to_pytimedelta(x).days/(24*60) +pd.Timedelta.to_pytimedelta(x).seconds/60)

In [165]:
df['time_elapsed'].head()
df.head(10)

0    24.0
1    60.0
2    21.0
3    22.0
4    26.0
Name: time_elapsed, dtype: float64

START_TIME            END_TIME             CATEGORY  \
0 2023-04-17 06:02:00 2023-04-17 06:26:00            ABLUTIONS   
1 2023-04-17 06:30:00 2023-04-17 07:30:00   HEALTH and FITNESS   
2 2023-04-17 07:35:00 2023-04-17 07:56:00            ABLUTIONS   
3 2023-04-17 08:04:00 2023-04-17 08:26:00                MEALS   
4 2023-04-17 08:32:00 2023-04-17 08:58:00  ONLINE INFOTAINMENT   
5 2023-04-17 09:00:00 2023-04-17 11:00:00             BUSINESS   
6 2023-04-17 11:02:00 2023-04-17 11:07:00                MEALS   
7 2023-04-17 11:08:00 2023-04-17 11:30:00  ONLINE INFOTAINMENT   
8 2023-04-17 11:32:00 2023-04-17 13:05:00             BUSINESS   
9 2023-04-17 13:05:00 2023-04-17 13:35:00                MEALS   

                  ACTIVITY                   LOCATION  time_elapsed  
0       WAKE UP AND WASHUP                       HOME          24.0  
1                    YOGA                 YOGA CENTER          60.0  
2             MORNING BATH                       HOME          21.0  
3                BREAKFAST                       HOME          22.0  
4  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR          26.0  
5        WORK AND MEETINGS                    OFFICE1         120.0  
6             COFFEE BREAK         OFFICE1 CAFFETERIA           5.0  
7  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR          22.0  
8        WORK AND MEETINGS                    OFFICE2          93.0  
9                    LUNCH         OFFICE2 CAFFETERIA          30.0

In [166]:
df['time_elapsed'].describe()

count    127.000000
mean      51.204724
std       41.590662
min        5.000000
25%       22.000000
50%       30.000000
75%       86.000000
max      180.000000
Name: time_elapsed, dtype: float64

In [167]:
#Capture Hour, Day, Month and Year of Schedule in a separate column
df['month'] = df['START_TIME'].dt.month
df['Year'] = df['START_TIME'].dt.year
df['Day'] = df['START_TIME'].dt.day
df['Hour'] = df['START_TIME'].dt.hour

In [168]:
#Capture day of week and rename to weekday names
df['day_of_week'] = df['START_TIME'].dt.dayofweek
days = {0:'Mon',1:'Tue',2:'Wed',3:'Thur',4:'Fri',5:'Sat',6:'Sun'}

df['day_of_week'] = df['day_of_week'].apply(lambda x: days[x])

In [169]:
df.head()

START_TIME            END_TIME             CATEGORY  \
0 2023-04-17 06:02:00 2023-04-17 06:26:00            ABLUTIONS   
1 2023-04-17 06:30:00 2023-04-17 07:30:00   HEALTH and FITNESS   
2 2023-04-17 07:35:00 2023-04-17 07:56:00            ABLUTIONS   
3 2023-04-17 08:04:00 2023-04-17 08:26:00                MEALS   
4 2023-04-17 08:32:00 2023-04-17 08:58:00  ONLINE INFOTAINMENT   

                  ACTIVITY                   LOCATION  time_elapsed  month  \
0       WAKE UP AND WASHUP                       HOME          24.0      4   
1                    YOGA                 YOGA CENTER          60.0      4   
2             MORNING BATH                       HOME          21.0      4   
3                BREAKFAST                       HOME          22.0      4   
4  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR          26.0      4   

   Year  Day  Hour day_of_week  
0  2023   17     6         Mon  
1  2023   17     6         Mon  
2  2023   17     7         Mon  
3  2023   17     8         Mon  
4  2023   17     8         Mon

In [170]:
#Rename the numbers in the Month column to calendar months
import calendar
df['month'] = df['month'].apply(lambda x: calendar.month_abbr[x])
df.head(10)

START_TIME            END_TIME             CATEGORY  \
0 2023-04-17 06:02:00 2023-04-17 06:26:00            ABLUTIONS   
1 2023-04-17 06:30:00 2023-04-17 07:30:00   HEALTH and FITNESS   
2 2023-04-17 07:35:00 2023-04-17 07:56:00            ABLUTIONS   
3 2023-04-17 08:04:00 2023-04-17 08:26:00                MEALS   
4 2023-04-17 08:32:00 2023-04-17 08:58:00  ONLINE INFOTAINMENT   
5 2023-04-17 09:00:00 2023-04-17 11:00:00             BUSINESS   
6 2023-04-17 11:02:00 2023-04-17 11:07:00                MEALS   
7 2023-04-17 11:08:00 2023-04-17 11:30:00  ONLINE INFOTAINMENT   
8 2023-04-17 11:32:00 2023-04-17 13:05:00             BUSINESS   
9 2023-04-17 13:05:00 2023-04-17 13:35:00                MEALS   

                  ACTIVITY                   LOCATION  time_elapsed month  \
0       WAKE UP AND WASHUP                       HOME          24.0   Apr   
1                    YOGA                 YOGA CENTER          60.0   Apr   
2             MORNING BATH                       HOME          21.0   Apr   
3                BREAKFAST                       HOME          22.0   Apr   
4  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR          26.0   Apr   
5        WORK AND MEETINGS                    OFFICE1         120.0   Apr   
6             COFFEE BREAK         OFFICE1 CAFFETERIA           5.0   Apr   
7  NEWS and SOCIAL NETWORK  ON ROAD BY CHAUFFERED CAR          22.0   Apr   
8        WORK AND MEETINGS                    OFFICE2          93.0   Apr   
9                    LUNCH         OFFICE2 CAFFETERIA          30.0   Apr   

   Year  Day  Hour day_of_week  
0  2023   17     6         Mon  
1  2023   17     6         Mon  
2  2023   17     7         Mon  
3  2023   17     8         Mon  
4  2023   17     8         Mon  
5  2023   17     9         Mon  
6  2023   17    11         Mon  
7  2023   17    11         Mon  
8  2023   17    11         Mon  
9  2023   17    13         Mon

In [171]:
print('CATEGORY in hrs')
df.groupby(['CATEGORY']).sum()['time_elapsed']/60.

CATEGORY in hrs


CATEGORY
ABLUTIONS               7.450000
BUSINESS               36.300000
ENTERTAINMENT           4.016667
HEALTH and FITNESS     11.316667
HOME MAINTENANCE        4.250000
MEALS                  15.850000
ONLINE INFOTAINMENT    17.516667
RELAXATION              6.466667
SHOPPING                0.833333
TEACHING                2.333333
TRAVEL                  2.050000
Name: time_elapsed, dtype: float64

In [173]:
df['time_elapsed'].sum()/60.

108.38333333333334

In [174]:
(df.groupby(['CATEGORY']).sum()['time_elapsed'])*100./df['time_elapsed'].sum()

CATEGORY
ABLUTIONS               6.873751
BUSINESS               33.492234
ENTERTAINMENT           3.705982
HEALTH and FITNESS     10.441335
HOME MAINTENANCE        3.921267
MEALS                  14.624020
ONLINE INFOTAINMENT    16.161771
RELAXATION              5.966477
SHOPPING                0.768876
TEACHING                2.152853
TRAVEL                  1.891435
Name: time_elapsed, dtype: float64

# END OF NB1 WORKSHOP